#!/usr/bin/env Rscript

#######################################################################
# This script will read a posterior distribution of trees generated by
# Mascot model in BEAST2 and count the number of transitions in the
# trait states. Usage:
# 
# Rscript countMascotStateChanges.R posterior.trees
#
# Written by G. Yebra, 30/06/20
#######################################################################


# Load the required libraries
library(treeio)
library(tidytree)

# Import the name of the trees file
args = commandArgs(trailingOnly=TRUE)

# # Create temporal output folder to store the trees
# parDir <- getwd()
# tempDir <- paste(parDir, "temp", sep="/")
# dir.create(tempDir)
# setwd(tempDir)

### Looping over a posterior tree distribution

inputname <- args[1]

# Extract the heading for the NEXUS
lines <- readLines(inputname)

endHead <- min(grep("tree STATE",lines))-1
heading <- lines[1:endHead]

# Extract the lines containing trees
tree_inds <- grep("tree STATE.*;",lines)

# Extract the first tree to figure out the trait states and the possible
# transitions between them
index <- tree_inds[1]
tree_nex <- c(heading, lines[index], "End;")
writeLines(tree_nex, "initialTree.nwk")
beastTree <- read.beast("initialTree.nwk")
beastTree_tb <- as_tibble(beastTree)
beastTree_tb <- sapply(beastTree_tb, as.character)
beastTree_df <- as.data.frame(beastTree_tb)
file.remove("initialTree.nwk")

lev_max <- levels(beastTree_df$max)
lev_trans <- paste(rep(lev_max, each = length(lev_max)), lev_max, sep = "_")

# Create the dataframe where transitions counts will be stored
sum_res <- data.frame(matrix(NA, nc=length(lev_trans)+1, nr=length(tree_inds)))
names(sum_res)<- c("nom",lev_trans)

# Loop over the lines with trees, and create and analyse each tree
for (tree in 1:length(tree_inds)){
  index <- tree_inds[tree]
  treeLine <- lines[index]
  treeLine_split <- strsplit(treeLine, " \\=\\ ")[[1]]
  treeState	<- strsplit(treeLine_split[1], " ")[[1]][2]
  #tree_nwk <- treeLine_split[2]
  
  # create the tree file to analyse
  tree_nex <- c(heading, treeLine, "End;")
  treeFileName <- paste("tree", treeState, ".nwk", sep = "")
  writeLines(tree_nex, treeFileName)
  
  # parse the tree to analyse and extract the node information
  beastTree <- read.beast(treeFileName)
  beastTree_tb <- as_tibble(beastTree)
  beastTree_tb <- sapply(beastTree_tb, as.character)
  beastTree_df <- as.data.frame(beastTree_tb)
  
  # get and store the 'max' value of the parent for each node
  par_max_list <- c()
  for(nd in 1:length(beastTree_df$parent)) {
    par <- as.character(beastTree_df$parent[nd])
    par_max <- as.character(beastTree_df[beastTree_df$node==par,]$max)
    par_max_list <- c(par_max_list, par_max)
  }
  
  # add the 'max' value of each node's parent as a new colum; and the type of
  # parent-to-node transition they represent
  beastTree_df$parent_max <- par_max_list
  beastTree_df$trans <- paste(beastTree_df$parent_max, beastTree_df$max, sep = "_")

  # summarise and store the counts for each type of transition 
  # in the global dataframe
  sum_res[tree,1] <- treeState
  for(tran in lev_trans) {
    sum_res[tree,tran] <- length(beastTree_df[beastTree_df$trans == tran,]$trans)
  }

  # remove the tree generated
  file.remove(treeFileName)
}

# # remove the temporal folder
# setwd(parDir)
# unlink(tempDir, recursive = TRUE)

# output the spreadsheet
outputname <- paste(inputname, "_output.csv", sep = "")
write.csv(sum_res, outputname)


